"use client";

import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { fetchAppointments } from "@/lib/api";
import { formatDateTime } from "@/lib/utils";
import {
  CalendarDays,
  CheckCircle2,
  Clock3,
  Search,
  Video,
} from "lucide-react";

export default function AppointmentsPage() {
  const [appointments, setAppointments] = useState<any[]>([]);

  useEffect(() => {
    fetchAppointments()
      .then((res) => setAppointments(Array.isArray(res) ? res : []))
      .catch(() => setAppointments([]));
  }, []);

  const rows = useMemo(
    () =>
      appointments.length
        ? appointments
        : [
            {
              id: 1,
              lead_name: "Angela Brooks",
              scheduled_for: new Date().toISOString(),
              status: "confirmed",
              source: "google",
            },
            {
              id: 2,
              lead_name: "Marcus Lee",
              scheduled_for: new Date(Date.now() + 86400000).toISOString(),
              status: "pending",
              source: "calendly",
            },
          ],
    [appointments]
  );

  return (
    <AppShell
      title="Appointments"
      subtitle="Track booked meetings, confirmation status, and scheduling sources from your outbound AI workflow."
    >
      <div className="space-y-6">
        <section className="rounded-[32px] border border-[#e6eefc] bg-white p-6 shadow-[0_10px_30px_rgba(21,59,122,0.05)]">
          <div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between">
            <div className="max-w-3xl">
              <div className="inline-flex items-center gap-2 rounded-full bg-[#eef4ff] px-3 py-1 text-xs font-semibold uppercase tracking-[0.18em] text-[#2563eb]">
                <CalendarDays className="h-3.5 w-3.5" />
                Appointment pipeline
              </div>

              <h2 className="mt-4 text-3xl font-semibold tracking-tight text-[#163b7a]">
                See the conversations your AI turned into meetings
              </h2>

              <p className="mt-3 text-sm leading-6 text-slate-500">
                Review booked appointments, monitor confirmation status, and keep
                your team focused on the outcomes generated by outbound automation.
              </p>
            </div>
          </div>
        </section>

        <section className="grid gap-4 md:grid-cols-3">
          <StatCard
            icon={<CalendarDays className="h-5 w-5" />}
            label="Total Appointments"
            value={String(rows.length)}
            hint="Meetings currently tracked"
          />
          <StatCard
            icon={<CheckCircle2 className="h-5 w-5" />}
            label="Confirmed"
            value={String(
              rows.filter(
                (appt) => String(appt.status || "").toLowerCase() === "confirmed"
              ).length
            )}
            hint="Ready for follow-up"
          />
          <StatCard
            icon={<Clock3 className="h-5 w-5" />}
            label="Pending"
            value={String(
              rows.filter(
                (appt) => String(appt.status || "").toLowerCase() === "pending"
              ).length
            )}
            hint="Needs confirmation"
          />
        </section>

        <section className="rounded-[32px] border border-[#e6eefc] bg-white p-5 shadow-[0_10px_30px_rgba(21,59,122,0.05)]">
          <div className="flex items-center gap-3 rounded-2xl border border-[#dbe7ff] bg-[#f7fbff] px-4 py-3">
            <Search className="h-4 w-4 text-[#2563eb]" />
            <input
              placeholder="Search appointments, leads, or scheduling sources"
              className="w-full bg-transparent text-sm text-slate-700 outline-none placeholder:text-slate-400"
            />
          </div>
        </section>

        <section className="grid gap-4">
          {rows.map((appt: any) => (
            <div
              key={appt.id}
              className="rounded-[32px] border border-[#e6eefc] bg-white p-5 shadow-[0_10px_30px_rgba(21,59,122,0.05)]"
            >
              <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                <div className="min-w-0">
                  <div className="text-lg font-semibold tracking-tight text-[#163b7a]">
                    {appt.lead_name || "Unnamed Appointment"}
                  </div>
                  <div className="mt-2 text-sm text-slate-500">
                    {formatDateTime(appt.scheduled_for)}
                  </div>
                </div>

                <div className="flex flex-wrap items-center gap-3">
                  <span className="inline-flex items-center gap-2 rounded-full border border-[#dbe7ff] bg-[#f7fbff] px-3 py-1 text-xs font-semibold uppercase tracking-wide text-slate-600">
                    <Video className="h-3.5 w-3.5 text-[#2563eb]" />
                    {appt.source || "manual"}
                  </span>

                  <span className={statusClass(appt.status)}>
                    {appt.status || "pending"}
                  </span>
                </div>
              </div>
            </div>
          ))}
        </section>
      </div>
    </AppShell>
  );
}

function StatCard({
  icon,
  label,
  value,
  hint,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
  hint: string;
}) {
  return (
    <div className="rounded-[28px] border border-[#e6eefc] bg-white p-5 shadow-[0_10px_30px_rgba(21,59,122,0.05)]">
      <div className="flex items-center justify-between">
        <div className="rounded-2xl bg-[#eef4ff] p-3 text-[#2563eb]">{icon}</div>
        <span className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">
          Overview
        </span>
      </div>

      <div className="mt-5 text-sm font-medium text-slate-500">{label}</div>
      <div className="mt-2 text-3xl font-semibold tracking-tight text-[#163b7a]">
        {value}
      </div>
      <div className="mt-2 text-sm text-slate-400">{hint}</div>
    </div>
  );
}

function statusClass(status: string) {
  const value = String(status || "pending").toLowerCase();

  if (value === "confirmed") {
    return "inline-flex rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-emerald-700";
  }

  if (value === "pending") {
    return "inline-flex rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-amber-700";
  }

  return "inline-flex rounded-full bg-[#eef4ff] px-3 py-1 text-xs font-semibold uppercase tracking-wide text-[#2563eb]";
}
